AllCops:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "log/**/*"
    - "node_modules/**/*"
    - !ruby/regexp /old_and_unused\.rb$/

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/LineLength:
  Max: 99

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 99
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  CountComments: false
  Max: 90

Naming/PredicateName:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Style/RedundantReturn:
  Enabled: true

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/Encoding:
  Enabled: false
